
default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode



development:
  <<: *default
  database: mouserails_development


test:
  <<: *default
  database: mouserails_test

production:
  <<: *default
  database: mouserails_production
